### PR TITLE
Replaced scroll override with animated navbar

### PR DESCRIPTION
**Pull request by pwstegman**
Removed fullpage.js and its scroll override, then added fade in background on navbar when the user scrolls down.

The navbar background will start as transparent when scrollY == 0. On scroll, a background color that matches the section will fade in and the HackGT logo will shrink to fit within the navbar.

### CODE REVIEW

**Comment by pwstegman** [comment]
Need to reimplement scroll to proper section on link click, will reopen when fixed

Edit: Added smooth scroll on link click

**Comment by mjkaufer** [comment]
<3 you pierce, can you remove the console logs tho

**Comment by pwstegman** [comment]
Removed the console log. I can also add polyfill for IE and Edge later today (needs a flexbox and window.scroll polyfill)

**Comment by petschekr** [comment]
@pwstegman You can safely ignore IE since we don't support that anymore for any of our apps or sites and Edge supports both of those

**Comment by kexin-zhang** [comment]
Hi! This looks amazing, thanks for the PR! I'm down to approve this once the console.logs are gone.

**Comment by ehsanmasdar** [comment]
I'm working on the travis failures, it's nothing to worry about for this PR

**Review by kexin-zhang — APPROVED** [review]

**Comment by pwstegman** [comment]
Found the issue with Edge. It uses a non standard getBoundingClientRect() function that doesn't return a y attribute. I'll work on a fix

Edit: getBoundingClientRect() issue fixed, also added polyfill for window.scroll since Edge uses a nonstandard window.scroll that doesn't allow options to be passed

**Review by petschekr — APPROVED** [review]
Awesome job! Thanks so much!

**Review by mjkaufer — APPROVED** [review]
pwstegman you're my heroooo

**Pull request merged**
